//add all the origins that are allowed to access the api 0.0.0.0/0
export const originList = [
    'http://localhost:4173',
    'http://localhost:4174',
    'http://localhost:5173',
    'http://localhost:3000',
    'https://sovseas.xyz',
    'https://www.sovseas.xyz',
    'https://www.demo.sovseas.xyz',
    'https://auth.sovseas.xyz',
    'https://sovseas.xyz/api',
    'https://auth.sovseas.xyz/api',
    'https://sovseas.xyz/api/claim-vote',
    'https://auth.sovseas.xyz/api/claim-vote',
    'https://sovseas.xyz/api/get-stats',
    'https://auth.sovseas.xyz/api/get-stats',
    'https://sovseas.xyz/api/get-stats',
    'https://www.sovseas.xyz/api/get-stats',
    'https://www.demo.sovseas.xyz/api/get-stats',
    'https://sovseas.xyz/api/claim-vote',
    'https://auth.sovseas.xyz/api/claim-vote',
    'https://sovseas.xyz/api/get-stats',
    'https://auth.sovseas.xyz/api/get-stats',
    'https://sovseas.xyz/api/get-stats',
    'https://www.sovseas.xyz/api/get-stats',
    'https://www.demo.sovseas.xyz/api/get-stats',
]