/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SovAdsManager {
  export type CampaignStruct = {
    id: BigNumberish;
    creator: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    metadata: string;
    active: boolean;
    spent: BigNumberish;
    paused: boolean;
  };

  export type CampaignStructOutput = [
    id: bigint,
    creator: string,
    token: string,
    amount: bigint,
    startTime: bigint,
    endTime: bigint,
    metadata: string,
    active: boolean,
    spent: bigint,
    paused: boolean
  ] & {
    id: bigint;
    creator: string;
    token: string;
    amount: bigint;
    startTime: bigint;
    endTime: bigint;
    metadata: string;
    active: boolean;
    spent: bigint;
    paused: boolean;
  };

  export type ClaimOrderStruct = {
    id: BigNumberish;
    publisher: AddressLike;
    campaignId: BigNumberish;
    requestedAmount: BigNumberish;
    approvedAmount: BigNumberish;
    processed: boolean;
    rejected: boolean;
    reason: string;
    createdAt: BigNumberish;
    processedAt: BigNumberish;
  };

  export type ClaimOrderStructOutput = [
    id: bigint,
    publisher: string,
    campaignId: bigint,
    requestedAmount: bigint,
    approvedAmount: bigint,
    processed: boolean,
    rejected: boolean,
    reason: string,
    createdAt: bigint,
    processedAt: bigint
  ] & {
    id: bigint;
    publisher: string;
    campaignId: bigint;
    requestedAmount: bigint;
    approvedAmount: bigint;
    processed: boolean;
    rejected: boolean;
    reason: string;
    createdAt: bigint;
    processedAt: bigint;
  };

  export type PublisherStruct = {
    wallet: AddressLike;
    sites: string[];
    banned: boolean;
    totalEarned: BigNumberish;
    totalClaimed: BigNumberish;
    verified: boolean;
    subscriptionDate: BigNumberish;
  };

  export type PublisherStructOutput = [
    wallet: string,
    sites: string[],
    banned: boolean,
    totalEarned: bigint,
    totalClaimed: bigint,
    verified: boolean,
    subscriptionDate: bigint
  ] & {
    wallet: string;
    sites: string[];
    banned: boolean;
    totalEarned: bigint;
    totalClaimed: bigint;
    verified: boolean;
    subscriptionDate: bigint;
  };
}

export interface SovAdsManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeCampaigns"
      | "addSite"
      | "addSupportedToken"
      | "banUser"
      | "bannedUsers"
      | "campaignCount"
      | "campaigns"
      | "claimOrderCount"
      | "claimOrders"
      | "collectFees"
      | "createCampaign"
      | "createClaimOrder"
      | "disburseFunds"
      | "editCampaign"
      | "feePercent"
      | "getActiveCampaignsCount"
      | "getCampaign"
      | "getClaimOrder"
      | "getPublisher"
      | "getPublisherSites"
      | "getSupportedTokens"
      | "getTotalProtocolFees"
      | "isPublisher"
      | "isUserBanned"
      | "owner"
      | "pause"
      | "pauseCampaign"
      | "paused"
      | "processClaimOrder"
      | "protocolFees"
      | "publishers"
      | "removeSite"
      | "removeSupportedToken"
      | "renounceOwnership"
      | "resumeCampaign"
      | "setFeePercent"
      | "subscribePublisher"
      | "supportedTokens"
      | "supportedTokensList"
      | "transferOwnership"
      | "unbanUser"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignCreated"
      | "CampaignEdited"
      | "CampaignPaused"
      | "CampaignResumed"
      | "ClaimOrderCreated"
      | "ClaimOrderProcessed"
      | "FeeCollected"
      | "FundsDisbursed"
      | "OwnershipTransferred"
      | "Paused"
      | "PublisherBanned"
      | "PublisherSubscribed"
      | "PublisherUnbanned"
      | "SiteAdded"
      | "SiteRemoved"
      | "SupportedTokenAdded"
      | "SupportedTokenRemoved"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeCampaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "addSite", values: [string]): string;
  encodeFunctionData(
    functionFragment: "addSupportedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "banUser",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "bannedUsers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimOrderCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimOrders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectFees",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createClaimOrder",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disburseFunds",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "editCampaign",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveCampaignsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublisher",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublisherSites",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalProtocolFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isPublisher",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isUserBanned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processClaimOrder",
    values: [BigNumberish, BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publishers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSite",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSupportedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resumeCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribePublisher",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokensList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unbanUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "activeCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addSite", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "banUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bannedUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimOrderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createClaimOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disburseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "editCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feePercent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveCampaignsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublisher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublisherSites",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalProtocolFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPublisher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUserBanned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processClaimOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "publishers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removeSite", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resumeCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscribePublisher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokensList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unbanUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    creator: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish,
    metadata: string
  ];
  export type OutputTuple = [
    id: bigint,
    creator: string,
    token: string,
    amount: bigint,
    startTime: bigint,
    endTime: bigint,
    metadata: string
  ];
  export interface OutputObject {
    id: bigint;
    creator: string;
    token: string;
    amount: bigint;
    startTime: bigint;
    endTime: bigint;
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignEditedEvent {
  export type InputTuple = [
    id: BigNumberish,
    newMetadata: string,
    newEndTime: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    newMetadata: string,
    newEndTime: bigint
  ];
  export interface OutputObject {
    id: bigint;
    newMetadata: string;
    newEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignPausedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignResumedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimOrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    publisher: AddressLike,
    campaignId: BigNumberish,
    requestedAmount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    publisher: string,
    campaignId: bigint,
    requestedAmount: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    publisher: string;
    campaignId: bigint;
    requestedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimOrderProcessedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    approvedAmount: BigNumberish,
    rejected: boolean,
    reason: string
  ];
  export type OutputTuple = [
    orderId: bigint,
    approvedAmount: bigint,
    rejected: boolean,
    reason: string
  ];
  export interface OutputObject {
    orderId: bigint;
    approvedAmount: bigint;
    rejected: boolean;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectedEvent {
  export type InputTuple = [admin: AddressLike, amount: BigNumberish];
  export type OutputTuple = [admin: string, amount: bigint];
  export interface OutputObject {
    admin: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDisbursedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublisherBannedEvent {
  export type InputTuple = [publisher: AddressLike, reason: string];
  export type OutputTuple = [publisher: string, reason: string];
  export interface OutputObject {
    publisher: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublisherSubscribedEvent {
  export type InputTuple = [
    publisher: AddressLike,
    sites: string[],
    subscriptionDate: BigNumberish
  ];
  export type OutputTuple = [
    publisher: string,
    sites: string[],
    subscriptionDate: bigint
  ];
  export interface OutputObject {
    publisher: string;
    sites: string[];
    subscriptionDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublisherUnbannedEvent {
  export type InputTuple = [publisher: AddressLike];
  export type OutputTuple = [publisher: string];
  export interface OutputObject {
    publisher: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SiteAddedEvent {
  export type InputTuple = [publisher: AddressLike, site: string];
  export type OutputTuple = [publisher: string, site: string];
  export interface OutputObject {
    publisher: string;
    site: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SiteRemovedEvent {
  export type InputTuple = [publisher: AddressLike, site: string];
  export type OutputTuple = [publisher: string, site: string];
  export interface OutputObject {
    publisher: string;
    site: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupportedTokenAddedEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupportedTokenRemovedEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SovAdsManager extends BaseContract {
  connect(runner?: ContractRunner | null): SovAdsManager;
  waitForDeployment(): Promise<this>;

  interface: SovAdsManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeCampaigns: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  addSite: TypedContractMethod<[_site: string], [void], "nonpayable">;

  addSupportedToken: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  banUser: TypedContractMethod<
    [_user: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;

  bannedUsers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  campaignCount: TypedContractMethod<[], [bigint], "view">;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        bigint,
        boolean
      ] & {
        id: bigint;
        creator: string;
        token: string;
        amount: bigint;
        startTime: bigint;
        endTime: bigint;
        metadata: string;
        active: boolean;
        spent: bigint;
        paused: boolean;
      }
    ],
    "view"
  >;

  claimOrderCount: TypedContractMethod<[], [bigint], "view">;

  claimOrders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        bigint,
        bigint
      ] & {
        id: bigint;
        publisher: string;
        campaignId: bigint;
        requestedAmount: bigint;
        approvedAmount: bigint;
        processed: boolean;
        rejected: boolean;
        reason: string;
        createdAt: bigint;
        processedAt: bigint;
      }
    ],
    "view"
  >;

  collectFees: TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  createCampaign: TypedContractMethod<
    [
      _token: AddressLike,
      _amount: BigNumberish,
      _duration: BigNumberish,
      _metadata: string
    ],
    [void],
    "nonpayable"
  >;

  createClaimOrder: TypedContractMethod<
    [_campaignId: BigNumberish, _requestedAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  disburseFunds: TypedContractMethod<
    [_campaignId: BigNumberish, _recipient: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  editCampaign: TypedContractMethod<
    [_campaignId: BigNumberish, _metadata: string, _newDuration: BigNumberish],
    [void],
    "nonpayable"
  >;

  feePercent: TypedContractMethod<[], [bigint], "view">;

  getActiveCampaignsCount: TypedContractMethod<[], [bigint], "view">;

  getCampaign: TypedContractMethod<
    [_campaignId: BigNumberish],
    [SovAdsManager.CampaignStructOutput],
    "view"
  >;

  getClaimOrder: TypedContractMethod<
    [_orderId: BigNumberish],
    [SovAdsManager.ClaimOrderStructOutput],
    "view"
  >;

  getPublisher: TypedContractMethod<
    [_publisher: AddressLike],
    [SovAdsManager.PublisherStructOutput],
    "view"
  >;

  getPublisherSites: TypedContractMethod<
    [_publisher: AddressLike],
    [string[]],
    "view"
  >;

  getSupportedTokens: TypedContractMethod<[], [string[]], "view">;

  getTotalProtocolFees: TypedContractMethod<[], [bigint], "view">;

  isPublisher: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isUserBanned: TypedContractMethod<[_user: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  pauseCampaign: TypedContractMethod<
    [_campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  paused: TypedContractMethod<[], [boolean], "view">;

  processClaimOrder: TypedContractMethod<
    [
      _orderId: BigNumberish,
      _approvedAmount: BigNumberish,
      _rejected: boolean,
      _reason: string
    ],
    [void],
    "nonpayable"
  >;

  protocolFees: TypedContractMethod<[], [bigint], "view">;

  publishers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint, bigint, boolean, bigint] & {
        wallet: string;
        banned: boolean;
        totalEarned: bigint;
        totalClaimed: bigint;
        verified: boolean;
        subscriptionDate: bigint;
      }
    ],
    "view"
  >;

  removeSite: TypedContractMethod<
    [_siteIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeSupportedToken: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resumeCampaign: TypedContractMethod<
    [_campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeePercent: TypedContractMethod<
    [_feePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  subscribePublisher: TypedContractMethod<
    [_sites: string[]],
    [void],
    "nonpayable"
  >;

  supportedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  supportedTokensList: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unbanUser: TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeCampaigns"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "addSite"
  ): TypedContractMethod<[_site: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addSupportedToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "banUser"
  ): TypedContractMethod<
    [_user: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bannedUsers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "campaignCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        bigint,
        boolean
      ] & {
        id: bigint;
        creator: string;
        token: string;
        amount: bigint;
        startTime: bigint;
        endTime: bigint;
        metadata: string;
        active: boolean;
        spent: bigint;
        paused: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimOrderCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimOrders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        bigint,
        bigint
      ] & {
        id: bigint;
        publisher: string;
        campaignId: bigint;
        requestedAmount: bigint;
        approvedAmount: bigint;
        processed: boolean;
        rejected: boolean;
        reason: string;
        createdAt: bigint;
        processedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "collectFees"
  ): TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _amount: BigNumberish,
      _duration: BigNumberish,
      _metadata: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createClaimOrder"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _requestedAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disburseFunds"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _recipient: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "editCampaign"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _metadata: string, _newDuration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getActiveCampaignsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [_campaignId: BigNumberish],
    [SovAdsManager.CampaignStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClaimOrder"
  ): TypedContractMethod<
    [_orderId: BigNumberish],
    [SovAdsManager.ClaimOrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPublisher"
  ): TypedContractMethod<
    [_publisher: AddressLike],
    [SovAdsManager.PublisherStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPublisherSites"
  ): TypedContractMethod<[_publisher: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSupportedTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalProtocolFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isPublisher"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isUserBanned"
  ): TypedContractMethod<[_user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pauseCampaign"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "processClaimOrder"
  ): TypedContractMethod<
    [
      _orderId: BigNumberish,
      _approvedAmount: BigNumberish,
      _rejected: boolean,
      _reason: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "protocolFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "publishers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint, bigint, boolean, bigint] & {
        wallet: string;
        banned: boolean;
        totalEarned: bigint;
        totalClaimed: bigint;
        verified: boolean;
        subscriptionDate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeSite"
  ): TypedContractMethod<[_siteIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeSupportedToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resumeCampaign"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeePercent"
  ): TypedContractMethod<[_feePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscribePublisher"
  ): TypedContractMethod<[_sites: string[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "supportedTokensList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unbanUser"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignEdited"
  ): TypedContractEvent<
    CampaignEditedEvent.InputTuple,
    CampaignEditedEvent.OutputTuple,
    CampaignEditedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignPaused"
  ): TypedContractEvent<
    CampaignPausedEvent.InputTuple,
    CampaignPausedEvent.OutputTuple,
    CampaignPausedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignResumed"
  ): TypedContractEvent<
    CampaignResumedEvent.InputTuple,
    CampaignResumedEvent.OutputTuple,
    CampaignResumedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimOrderCreated"
  ): TypedContractEvent<
    ClaimOrderCreatedEvent.InputTuple,
    ClaimOrderCreatedEvent.OutputTuple,
    ClaimOrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimOrderProcessed"
  ): TypedContractEvent<
    ClaimOrderProcessedEvent.InputTuple,
    ClaimOrderProcessedEvent.OutputTuple,
    ClaimOrderProcessedEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollected"
  ): TypedContractEvent<
    FeeCollectedEvent.InputTuple,
    FeeCollectedEvent.OutputTuple,
    FeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "FundsDisbursed"
  ): TypedContractEvent<
    FundsDisbursedEvent.InputTuple,
    FundsDisbursedEvent.OutputTuple,
    FundsDisbursedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PublisherBanned"
  ): TypedContractEvent<
    PublisherBannedEvent.InputTuple,
    PublisherBannedEvent.OutputTuple,
    PublisherBannedEvent.OutputObject
  >;
  getEvent(
    key: "PublisherSubscribed"
  ): TypedContractEvent<
    PublisherSubscribedEvent.InputTuple,
    PublisherSubscribedEvent.OutputTuple,
    PublisherSubscribedEvent.OutputObject
  >;
  getEvent(
    key: "PublisherUnbanned"
  ): TypedContractEvent<
    PublisherUnbannedEvent.InputTuple,
    PublisherUnbannedEvent.OutputTuple,
    PublisherUnbannedEvent.OutputObject
  >;
  getEvent(
    key: "SiteAdded"
  ): TypedContractEvent<
    SiteAddedEvent.InputTuple,
    SiteAddedEvent.OutputTuple,
    SiteAddedEvent.OutputObject
  >;
  getEvent(
    key: "SiteRemoved"
  ): TypedContractEvent<
    SiteRemovedEvent.InputTuple,
    SiteRemovedEvent.OutputTuple,
    SiteRemovedEvent.OutputObject
  >;
  getEvent(
    key: "SupportedTokenAdded"
  ): TypedContractEvent<
    SupportedTokenAddedEvent.InputTuple,
    SupportedTokenAddedEvent.OutputTuple,
    SupportedTokenAddedEvent.OutputObject
  >;
  getEvent(
    key: "SupportedTokenRemoved"
  ): TypedContractEvent<
    SupportedTokenRemovedEvent.InputTuple,
    SupportedTokenRemovedEvent.OutputTuple,
    SupportedTokenRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "CampaignCreated(uint256,address,address,uint256,uint256,uint256,string)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignEdited(uint256,string,uint256)": TypedContractEvent<
      CampaignEditedEvent.InputTuple,
      CampaignEditedEvent.OutputTuple,
      CampaignEditedEvent.OutputObject
    >;
    CampaignEdited: TypedContractEvent<
      CampaignEditedEvent.InputTuple,
      CampaignEditedEvent.OutputTuple,
      CampaignEditedEvent.OutputObject
    >;

    "CampaignPaused(uint256)": TypedContractEvent<
      CampaignPausedEvent.InputTuple,
      CampaignPausedEvent.OutputTuple,
      CampaignPausedEvent.OutputObject
    >;
    CampaignPaused: TypedContractEvent<
      CampaignPausedEvent.InputTuple,
      CampaignPausedEvent.OutputTuple,
      CampaignPausedEvent.OutputObject
    >;

    "CampaignResumed(uint256)": TypedContractEvent<
      CampaignResumedEvent.InputTuple,
      CampaignResumedEvent.OutputTuple,
      CampaignResumedEvent.OutputObject
    >;
    CampaignResumed: TypedContractEvent<
      CampaignResumedEvent.InputTuple,
      CampaignResumedEvent.OutputTuple,
      CampaignResumedEvent.OutputObject
    >;

    "ClaimOrderCreated(uint256,address,uint256,uint256)": TypedContractEvent<
      ClaimOrderCreatedEvent.InputTuple,
      ClaimOrderCreatedEvent.OutputTuple,
      ClaimOrderCreatedEvent.OutputObject
    >;
    ClaimOrderCreated: TypedContractEvent<
      ClaimOrderCreatedEvent.InputTuple,
      ClaimOrderCreatedEvent.OutputTuple,
      ClaimOrderCreatedEvent.OutputObject
    >;

    "ClaimOrderProcessed(uint256,uint256,bool,string)": TypedContractEvent<
      ClaimOrderProcessedEvent.InputTuple,
      ClaimOrderProcessedEvent.OutputTuple,
      ClaimOrderProcessedEvent.OutputObject
    >;
    ClaimOrderProcessed: TypedContractEvent<
      ClaimOrderProcessedEvent.InputTuple,
      ClaimOrderProcessedEvent.OutputTuple,
      ClaimOrderProcessedEvent.OutputObject
    >;

    "FeeCollected(address,uint256)": TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;
    FeeCollected: TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;

    "FundsDisbursed(uint256,address,uint256)": TypedContractEvent<
      FundsDisbursedEvent.InputTuple,
      FundsDisbursedEvent.OutputTuple,
      FundsDisbursedEvent.OutputObject
    >;
    FundsDisbursed: TypedContractEvent<
      FundsDisbursedEvent.InputTuple,
      FundsDisbursedEvent.OutputTuple,
      FundsDisbursedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PublisherBanned(address,string)": TypedContractEvent<
      PublisherBannedEvent.InputTuple,
      PublisherBannedEvent.OutputTuple,
      PublisherBannedEvent.OutputObject
    >;
    PublisherBanned: TypedContractEvent<
      PublisherBannedEvent.InputTuple,
      PublisherBannedEvent.OutputTuple,
      PublisherBannedEvent.OutputObject
    >;

    "PublisherSubscribed(address,string[],uint256)": TypedContractEvent<
      PublisherSubscribedEvent.InputTuple,
      PublisherSubscribedEvent.OutputTuple,
      PublisherSubscribedEvent.OutputObject
    >;
    PublisherSubscribed: TypedContractEvent<
      PublisherSubscribedEvent.InputTuple,
      PublisherSubscribedEvent.OutputTuple,
      PublisherSubscribedEvent.OutputObject
    >;

    "PublisherUnbanned(address)": TypedContractEvent<
      PublisherUnbannedEvent.InputTuple,
      PublisherUnbannedEvent.OutputTuple,
      PublisherUnbannedEvent.OutputObject
    >;
    PublisherUnbanned: TypedContractEvent<
      PublisherUnbannedEvent.InputTuple,
      PublisherUnbannedEvent.OutputTuple,
      PublisherUnbannedEvent.OutputObject
    >;

    "SiteAdded(address,string)": TypedContractEvent<
      SiteAddedEvent.InputTuple,
      SiteAddedEvent.OutputTuple,
      SiteAddedEvent.OutputObject
    >;
    SiteAdded: TypedContractEvent<
      SiteAddedEvent.InputTuple,
      SiteAddedEvent.OutputTuple,
      SiteAddedEvent.OutputObject
    >;

    "SiteRemoved(address,string)": TypedContractEvent<
      SiteRemovedEvent.InputTuple,
      SiteRemovedEvent.OutputTuple,
      SiteRemovedEvent.OutputObject
    >;
    SiteRemoved: TypedContractEvent<
      SiteRemovedEvent.InputTuple,
      SiteRemovedEvent.OutputTuple,
      SiteRemovedEvent.OutputObject
    >;

    "SupportedTokenAdded(address)": TypedContractEvent<
      SupportedTokenAddedEvent.InputTuple,
      SupportedTokenAddedEvent.OutputTuple,
      SupportedTokenAddedEvent.OutputObject
    >;
    SupportedTokenAdded: TypedContractEvent<
      SupportedTokenAddedEvent.InputTuple,
      SupportedTokenAddedEvent.OutputTuple,
      SupportedTokenAddedEvent.OutputObject
    >;

    "SupportedTokenRemoved(address)": TypedContractEvent<
      SupportedTokenRemovedEvent.InputTuple,
      SupportedTokenRemovedEvent.OutputTuple,
      SupportedTokenRemovedEvent.OutputObject
    >;
    SupportedTokenRemoved: TypedContractEvent<
      SupportedTokenRemovedEvent.InputTuple,
      SupportedTokenRemovedEvent.OutputTuple,
      SupportedTokenRemovedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
