/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace SovAdsManager {
  export type CampaignStruct = {
    id: PromiseOrValue<BigNumberish>;
    creator: PromiseOrValue<string>;
    token: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
    startTime: PromiseOrValue<BigNumberish>;
    endTime: PromiseOrValue<BigNumberish>;
    metadata: PromiseOrValue<string>;
    active: PromiseOrValue<boolean>;
    spent: PromiseOrValue<BigNumberish>;
    paused: PromiseOrValue<boolean>;
  };

  export type CampaignStructOutput = [
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    boolean,
    BigNumber,
    boolean
  ] & {
    id: BigNumber;
    creator: string;
    token: string;
    amount: BigNumber;
    startTime: BigNumber;
    endTime: BigNumber;
    metadata: string;
    active: boolean;
    spent: BigNumber;
    paused: boolean;
  };

  export type ClaimOrderStruct = {
    id: PromiseOrValue<BigNumberish>;
    publisher: PromiseOrValue<string>;
    campaignId: PromiseOrValue<BigNumberish>;
    requestedAmount: PromiseOrValue<BigNumberish>;
    approvedAmount: PromiseOrValue<BigNumberish>;
    processed: PromiseOrValue<boolean>;
    rejected: PromiseOrValue<boolean>;
    reason: PromiseOrValue<string>;
    createdAt: PromiseOrValue<BigNumberish>;
    processedAt: PromiseOrValue<BigNumberish>;
  };

  export type ClaimOrderStructOutput = [
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean,
    boolean,
    string,
    BigNumber,
    BigNumber
  ] & {
    id: BigNumber;
    publisher: string;
    campaignId: BigNumber;
    requestedAmount: BigNumber;
    approvedAmount: BigNumber;
    processed: boolean;
    rejected: boolean;
    reason: string;
    createdAt: BigNumber;
    processedAt: BigNumber;
  };

  export type PublisherStruct = {
    wallet: PromiseOrValue<string>;
    sites: PromiseOrValue<string>[];
    banned: PromiseOrValue<boolean>;
    totalEarned: PromiseOrValue<BigNumberish>;
    totalClaimed: PromiseOrValue<BigNumberish>;
    verified: PromiseOrValue<boolean>;
    subscriptionDate: PromiseOrValue<BigNumberish>;
  };

  export type PublisherStructOutput = [
    string,
    string[],
    boolean,
    BigNumber,
    BigNumber,
    boolean,
    BigNumber
  ] & {
    wallet: string;
    sites: string[];
    banned: boolean;
    totalEarned: BigNumber;
    totalClaimed: BigNumber;
    verified: boolean;
    subscriptionDate: BigNumber;
  };
}

export interface SovAdsManagerInterface extends utils.Interface {
  functions: {
    "activeCampaigns(uint256)": FunctionFragment;
    "addSite(string)": FunctionFragment;
    "addSupportedToken(address)": FunctionFragment;
    "banUser(address,string)": FunctionFragment;
    "bannedUsers(address)": FunctionFragment;
    "campaignCount()": FunctionFragment;
    "campaigns(uint256)": FunctionFragment;
    "claimOrderCount()": FunctionFragment;
    "claimOrders(uint256)": FunctionFragment;
    "collectFees(address,uint256)": FunctionFragment;
    "createCampaign(address,uint256,uint256,string)": FunctionFragment;
    "createClaimOrder(uint256,uint256)": FunctionFragment;
    "disburseFunds(uint256,address,uint256)": FunctionFragment;
    "editCampaign(uint256,string,uint256)": FunctionFragment;
    "feePercent()": FunctionFragment;
    "getActiveCampaignsCount()": FunctionFragment;
    "getCampaign(uint256)": FunctionFragment;
    "getClaimOrder(uint256)": FunctionFragment;
    "getPublisher(address)": FunctionFragment;
    "getPublisherSites(address)": FunctionFragment;
    "getSupportedTokens()": FunctionFragment;
    "getTotalProtocolFees()": FunctionFragment;
    "isPublisher(address)": FunctionFragment;
    "isUserBanned(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "pauseCampaign(uint256)": FunctionFragment;
    "paused()": FunctionFragment;
    "processClaimOrder(uint256,uint256,bool,string)": FunctionFragment;
    "protocolFees()": FunctionFragment;
    "publishers(address)": FunctionFragment;
    "removeSite(uint256)": FunctionFragment;
    "removeSupportedToken(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "resumeCampaign(uint256)": FunctionFragment;
    "setFeePercent(uint256)": FunctionFragment;
    "subscribePublisher(string[])": FunctionFragment;
    "supportedTokens(address)": FunctionFragment;
    "supportedTokensList(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unbanUser(address)": FunctionFragment;
    "unpause()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "activeCampaigns"
      | "addSite"
      | "addSupportedToken"
      | "banUser"
      | "bannedUsers"
      | "campaignCount"
      | "campaigns"
      | "claimOrderCount"
      | "claimOrders"
      | "collectFees"
      | "createCampaign"
      | "createClaimOrder"
      | "disburseFunds"
      | "editCampaign"
      | "feePercent"
      | "getActiveCampaignsCount"
      | "getCampaign"
      | "getClaimOrder"
      | "getPublisher"
      | "getPublisherSites"
      | "getSupportedTokens"
      | "getTotalProtocolFees"
      | "isPublisher"
      | "isUserBanned"
      | "owner"
      | "pause"
      | "pauseCampaign"
      | "paused"
      | "processClaimOrder"
      | "protocolFees"
      | "publishers"
      | "removeSite"
      | "removeSupportedToken"
      | "renounceOwnership"
      | "resumeCampaign"
      | "setFeePercent"
      | "subscribePublisher"
      | "supportedTokens"
      | "supportedTokensList"
      | "transferOwnership"
      | "unbanUser"
      | "unpause"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activeCampaigns",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "addSite",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addSupportedToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "banUser",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "bannedUsers",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimOrderCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimOrders",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "collectFees",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createClaimOrder",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "disburseFunds",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "editCampaign",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "feePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveCampaignsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimOrder",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublisher",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublisherSites",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalProtocolFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isPublisher",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isUserBanned",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseCampaign",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processClaimOrder",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publishers",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSite",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSupportedToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resumeCampaign",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeePercent",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribePublisher",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokensList",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "unbanUser",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "activeCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addSite", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "banUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bannedUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimOrderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createClaimOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disburseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "editCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feePercent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveCampaignsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublisher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublisherSites",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalProtocolFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPublisher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUserBanned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processClaimOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "publishers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removeSite", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resumeCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscribePublisher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokensList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unbanUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;

  events: {
    "CampaignCreated(uint256,address,address,uint256,uint256,uint256,string)": EventFragment;
    "CampaignEdited(uint256,string,uint256)": EventFragment;
    "CampaignPaused(uint256)": EventFragment;
    "CampaignResumed(uint256)": EventFragment;
    "ClaimOrderCreated(uint256,address,uint256,uint256)": EventFragment;
    "ClaimOrderProcessed(uint256,uint256,bool,string)": EventFragment;
    "FeeCollected(address,uint256)": EventFragment;
    "FundsDisbursed(uint256,address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "PublisherBanned(address,string)": EventFragment;
    "PublisherSubscribed(address,string[],uint256)": EventFragment;
    "PublisherUnbanned(address)": EventFragment;
    "SiteAdded(address,string)": EventFragment;
    "SiteRemoved(address,string)": EventFragment;
    "SupportedTokenAdded(address)": EventFragment;
    "SupportedTokenRemoved(address)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CampaignCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CampaignEdited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CampaignPaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CampaignResumed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimOrderCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimOrderProcessed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeeCollected"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FundsDisbursed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PublisherBanned"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PublisherSubscribed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PublisherUnbanned"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SiteAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SiteRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SupportedTokenAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SupportedTokenRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface CampaignCreatedEventObject {
  id: BigNumber;
  creator: string;
  token: string;
  amount: BigNumber;
  startTime: BigNumber;
  endTime: BigNumber;
  metadata: string;
}
export type CampaignCreatedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, BigNumber, BigNumber, string],
  CampaignCreatedEventObject
>;

export type CampaignCreatedEventFilter = TypedEventFilter<CampaignCreatedEvent>;

export interface CampaignEditedEventObject {
  id: BigNumber;
  newMetadata: string;
  newEndTime: BigNumber;
}
export type CampaignEditedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  CampaignEditedEventObject
>;

export type CampaignEditedEventFilter = TypedEventFilter<CampaignEditedEvent>;

export interface CampaignPausedEventObject {
  id: BigNumber;
}
export type CampaignPausedEvent = TypedEvent<
  [BigNumber],
  CampaignPausedEventObject
>;

export type CampaignPausedEventFilter = TypedEventFilter<CampaignPausedEvent>;

export interface CampaignResumedEventObject {
  id: BigNumber;
}
export type CampaignResumedEvent = TypedEvent<
  [BigNumber],
  CampaignResumedEventObject
>;

export type CampaignResumedEventFilter = TypedEventFilter<CampaignResumedEvent>;

export interface ClaimOrderCreatedEventObject {
  orderId: BigNumber;
  publisher: string;
  campaignId: BigNumber;
  requestedAmount: BigNumber;
}
export type ClaimOrderCreatedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber],
  ClaimOrderCreatedEventObject
>;

export type ClaimOrderCreatedEventFilter =
  TypedEventFilter<ClaimOrderCreatedEvent>;

export interface ClaimOrderProcessedEventObject {
  orderId: BigNumber;
  approvedAmount: BigNumber;
  rejected: boolean;
  reason: string;
}
export type ClaimOrderProcessedEvent = TypedEvent<
  [BigNumber, BigNumber, boolean, string],
  ClaimOrderProcessedEventObject
>;

export type ClaimOrderProcessedEventFilter =
  TypedEventFilter<ClaimOrderProcessedEvent>;

export interface FeeCollectedEventObject {
  admin: string;
  amount: BigNumber;
}
export type FeeCollectedEvent = TypedEvent<
  [string, BigNumber],
  FeeCollectedEventObject
>;

export type FeeCollectedEventFilter = TypedEventFilter<FeeCollectedEvent>;

export interface FundsDisbursedEventObject {
  campaignId: BigNumber;
  recipient: string;
  amount: BigNumber;
}
export type FundsDisbursedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  FundsDisbursedEventObject
>;

export type FundsDisbursedEventFilter = TypedEventFilter<FundsDisbursedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface PublisherBannedEventObject {
  publisher: string;
  reason: string;
}
export type PublisherBannedEvent = TypedEvent<
  [string, string],
  PublisherBannedEventObject
>;

export type PublisherBannedEventFilter = TypedEventFilter<PublisherBannedEvent>;

export interface PublisherSubscribedEventObject {
  publisher: string;
  sites: string[];
  subscriptionDate: BigNumber;
}
export type PublisherSubscribedEvent = TypedEvent<
  [string, string[], BigNumber],
  PublisherSubscribedEventObject
>;

export type PublisherSubscribedEventFilter =
  TypedEventFilter<PublisherSubscribedEvent>;

export interface PublisherUnbannedEventObject {
  publisher: string;
}
export type PublisherUnbannedEvent = TypedEvent<
  [string],
  PublisherUnbannedEventObject
>;

export type PublisherUnbannedEventFilter =
  TypedEventFilter<PublisherUnbannedEvent>;

export interface SiteAddedEventObject {
  publisher: string;
  site: string;
}
export type SiteAddedEvent = TypedEvent<[string, string], SiteAddedEventObject>;

export type SiteAddedEventFilter = TypedEventFilter<SiteAddedEvent>;

export interface SiteRemovedEventObject {
  publisher: string;
  site: string;
}
export type SiteRemovedEvent = TypedEvent<
  [string, string],
  SiteRemovedEventObject
>;

export type SiteRemovedEventFilter = TypedEventFilter<SiteRemovedEvent>;

export interface SupportedTokenAddedEventObject {
  token: string;
}
export type SupportedTokenAddedEvent = TypedEvent<
  [string],
  SupportedTokenAddedEventObject
>;

export type SupportedTokenAddedEventFilter =
  TypedEventFilter<SupportedTokenAddedEvent>;

export interface SupportedTokenRemovedEventObject {
  token: string;
}
export type SupportedTokenRemovedEvent = TypedEvent<
  [string],
  SupportedTokenRemovedEventObject
>;

export type SupportedTokenRemovedEventFilter =
  TypedEventFilter<SupportedTokenRemovedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface SovAdsManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SovAdsManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    activeCampaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    addSite(
      _site: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addSupportedToken(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    banUser(
      _user: PromiseOrValue<string>,
      _reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    bannedUsers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    campaignCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    campaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        boolean,
        BigNumber,
        boolean
      ] & {
        id: BigNumber;
        creator: string;
        token: string;
        amount: BigNumber;
        startTime: BigNumber;
        endTime: BigNumber;
        metadata: string;
        active: boolean;
        spent: BigNumber;
        paused: boolean;
      }
    >;

    claimOrderCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    claimOrders(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        boolean,
        string,
        BigNumber,
        BigNumber
      ] & {
        id: BigNumber;
        publisher: string;
        campaignId: BigNumber;
        requestedAmount: BigNumber;
        approvedAmount: BigNumber;
        processed: boolean;
        rejected: boolean;
        reason: string;
        createdAt: BigNumber;
        processedAt: BigNumber;
      }
    >;

    collectFees(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createCampaign(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createClaimOrder(
      _campaignId: PromiseOrValue<BigNumberish>,
      _requestedAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    disburseFunds(
      _campaignId: PromiseOrValue<BigNumberish>,
      _recipient: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    editCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      _newDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    feePercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    getActiveCampaignsCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[SovAdsManager.CampaignStructOutput]>;

    getClaimOrder(
      _orderId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[SovAdsManager.ClaimOrderStructOutput]>;

    getPublisher(
      _publisher: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[SovAdsManager.PublisherStructOutput]>;

    getPublisherSites(
      _publisher: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getSupportedTokens(overrides?: CallOverrides): Promise<[string[]]>;

    getTotalProtocolFees(overrides?: CallOverrides): Promise<[BigNumber]>;

    isPublisher(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isUserBanned(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pauseCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    processClaimOrder(
      _orderId: PromiseOrValue<BigNumberish>,
      _approvedAmount: PromiseOrValue<BigNumberish>,
      _rejected: PromiseOrValue<boolean>,
      _reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    protocolFees(overrides?: CallOverrides): Promise<[BigNumber]>;

    publishers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, boolean, BigNumber, BigNumber, boolean, BigNumber] & {
        wallet: string;
        banned: boolean;
        totalEarned: BigNumber;
        totalClaimed: BigNumber;
        verified: boolean;
        subscriptionDate: BigNumber;
      }
    >;

    removeSite(
      _siteIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeSupportedToken(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    resumeCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFeePercent(
      _feePercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    subscribePublisher(
      _sites: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    supportedTokensList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unbanUser(
      _user: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  activeCampaigns(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  addSite(
    _site: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addSupportedToken(
    _token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  banUser(
    _user: PromiseOrValue<string>,
    _reason: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  bannedUsers(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  campaignCount(overrides?: CallOverrides): Promise<BigNumber>;

  campaigns(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      string,
      boolean,
      BigNumber,
      boolean
    ] & {
      id: BigNumber;
      creator: string;
      token: string;
      amount: BigNumber;
      startTime: BigNumber;
      endTime: BigNumber;
      metadata: string;
      active: boolean;
      spent: BigNumber;
      paused: boolean;
    }
  >;

  claimOrderCount(overrides?: CallOverrides): Promise<BigNumber>;

  claimOrders(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      boolean,
      boolean,
      string,
      BigNumber,
      BigNumber
    ] & {
      id: BigNumber;
      publisher: string;
      campaignId: BigNumber;
      requestedAmount: BigNumber;
      approvedAmount: BigNumber;
      processed: boolean;
      rejected: boolean;
      reason: string;
      createdAt: BigNumber;
      processedAt: BigNumber;
    }
  >;

  collectFees(
    _token: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createCampaign(
    _token: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    _duration: PromiseOrValue<BigNumberish>,
    _metadata: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createClaimOrder(
    _campaignId: PromiseOrValue<BigNumberish>,
    _requestedAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  disburseFunds(
    _campaignId: PromiseOrValue<BigNumberish>,
    _recipient: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  editCampaign(
    _campaignId: PromiseOrValue<BigNumberish>,
    _metadata: PromiseOrValue<string>,
    _newDuration: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  feePercent(overrides?: CallOverrides): Promise<BigNumber>;

  getActiveCampaignsCount(overrides?: CallOverrides): Promise<BigNumber>;

  getCampaign(
    _campaignId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<SovAdsManager.CampaignStructOutput>;

  getClaimOrder(
    _orderId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<SovAdsManager.ClaimOrderStructOutput>;

  getPublisher(
    _publisher: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<SovAdsManager.PublisherStructOutput>;

  getPublisherSites(
    _publisher: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getSupportedTokens(overrides?: CallOverrides): Promise<string[]>;

  getTotalProtocolFees(overrides?: CallOverrides): Promise<BigNumber>;

  isPublisher(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isUserBanned(
    _user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pauseCampaign(
    _campaignId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  processClaimOrder(
    _orderId: PromiseOrValue<BigNumberish>,
    _approvedAmount: PromiseOrValue<BigNumberish>,
    _rejected: PromiseOrValue<boolean>,
    _reason: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  protocolFees(overrides?: CallOverrides): Promise<BigNumber>;

  publishers(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, boolean, BigNumber, BigNumber, boolean, BigNumber] & {
      wallet: string;
      banned: boolean;
      totalEarned: BigNumber;
      totalClaimed: BigNumber;
      verified: boolean;
      subscriptionDate: BigNumber;
    }
  >;

  removeSite(
    _siteIndex: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeSupportedToken(
    _token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  resumeCampaign(
    _campaignId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFeePercent(
    _feePercent: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  subscribePublisher(
    _sites: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportedTokens(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  supportedTokensList(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unbanUser(
    _user: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    activeCampaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addSite(
      _site: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addSupportedToken(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    banUser(
      _user: PromiseOrValue<string>,
      _reason: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    bannedUsers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    campaignCount(overrides?: CallOverrides): Promise<BigNumber>;

    campaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        boolean,
        BigNumber,
        boolean
      ] & {
        id: BigNumber;
        creator: string;
        token: string;
        amount: BigNumber;
        startTime: BigNumber;
        endTime: BigNumber;
        metadata: string;
        active: boolean;
        spent: BigNumber;
        paused: boolean;
      }
    >;

    claimOrderCount(overrides?: CallOverrides): Promise<BigNumber>;

    claimOrders(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        boolean,
        string,
        BigNumber,
        BigNumber
      ] & {
        id: BigNumber;
        publisher: string;
        campaignId: BigNumber;
        requestedAmount: BigNumber;
        approvedAmount: BigNumber;
        processed: boolean;
        rejected: boolean;
        reason: string;
        createdAt: BigNumber;
        processedAt: BigNumber;
      }
    >;

    collectFees(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createCampaign(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    createClaimOrder(
      _campaignId: PromiseOrValue<BigNumberish>,
      _requestedAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    disburseFunds(
      _campaignId: PromiseOrValue<BigNumberish>,
      _recipient: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    editCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      _newDuration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    feePercent(overrides?: CallOverrides): Promise<BigNumber>;

    getActiveCampaignsCount(overrides?: CallOverrides): Promise<BigNumber>;

    getCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<SovAdsManager.CampaignStructOutput>;

    getClaimOrder(
      _orderId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<SovAdsManager.ClaimOrderStructOutput>;

    getPublisher(
      _publisher: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<SovAdsManager.PublisherStructOutput>;

    getPublisherSites(
      _publisher: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getSupportedTokens(overrides?: CallOverrides): Promise<string[]>;

    getTotalProtocolFees(overrides?: CallOverrides): Promise<BigNumber>;

    isPublisher(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isUserBanned(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    pauseCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    processClaimOrder(
      _orderId: PromiseOrValue<BigNumberish>,
      _approvedAmount: PromiseOrValue<BigNumberish>,
      _rejected: PromiseOrValue<boolean>,
      _reason: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    protocolFees(overrides?: CallOverrides): Promise<BigNumber>;

    publishers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, boolean, BigNumber, BigNumber, boolean, BigNumber] & {
        wallet: string;
        banned: boolean;
        totalEarned: BigNumber;
        totalClaimed: BigNumber;
        verified: boolean;
        subscriptionDate: BigNumber;
      }
    >;

    removeSite(
      _siteIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeSupportedToken(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    resumeCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeePercent(
      _feePercent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    subscribePublisher(
      _sites: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    supportedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    supportedTokensList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unbanUser(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "CampaignCreated(uint256,address,address,uint256,uint256,uint256,string)"(
      id?: PromiseOrValue<BigNumberish> | null,
      creator?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: null,
      startTime?: null,
      endTime?: null,
      metadata?: null
    ): CampaignCreatedEventFilter;
    CampaignCreated(
      id?: PromiseOrValue<BigNumberish> | null,
      creator?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: null,
      startTime?: null,
      endTime?: null,
      metadata?: null
    ): CampaignCreatedEventFilter;

    "CampaignEdited(uint256,string,uint256)"(
      id?: PromiseOrValue<BigNumberish> | null,
      newMetadata?: null,
      newEndTime?: null
    ): CampaignEditedEventFilter;
    CampaignEdited(
      id?: PromiseOrValue<BigNumberish> | null,
      newMetadata?: null,
      newEndTime?: null
    ): CampaignEditedEventFilter;

    "CampaignPaused(uint256)"(
      id?: PromiseOrValue<BigNumberish> | null
    ): CampaignPausedEventFilter;
    CampaignPaused(
      id?: PromiseOrValue<BigNumberish> | null
    ): CampaignPausedEventFilter;

    "CampaignResumed(uint256)"(
      id?: PromiseOrValue<BigNumberish> | null
    ): CampaignResumedEventFilter;
    CampaignResumed(
      id?: PromiseOrValue<BigNumberish> | null
    ): CampaignResumedEventFilter;

    "ClaimOrderCreated(uint256,address,uint256,uint256)"(
      orderId?: PromiseOrValue<BigNumberish> | null,
      publisher?: PromiseOrValue<string> | null,
      campaignId?: PromiseOrValue<BigNumberish> | null,
      requestedAmount?: null
    ): ClaimOrderCreatedEventFilter;
    ClaimOrderCreated(
      orderId?: PromiseOrValue<BigNumberish> | null,
      publisher?: PromiseOrValue<string> | null,
      campaignId?: PromiseOrValue<BigNumberish> | null,
      requestedAmount?: null
    ): ClaimOrderCreatedEventFilter;

    "ClaimOrderProcessed(uint256,uint256,bool,string)"(
      orderId?: PromiseOrValue<BigNumberish> | null,
      approvedAmount?: null,
      rejected?: null,
      reason?: null
    ): ClaimOrderProcessedEventFilter;
    ClaimOrderProcessed(
      orderId?: PromiseOrValue<BigNumberish> | null,
      approvedAmount?: null,
      rejected?: null,
      reason?: null
    ): ClaimOrderProcessedEventFilter;

    "FeeCollected(address,uint256)"(
      admin?: PromiseOrValue<string> | null,
      amount?: null
    ): FeeCollectedEventFilter;
    FeeCollected(
      admin?: PromiseOrValue<string> | null,
      amount?: null
    ): FeeCollectedEventFilter;

    "FundsDisbursed(uint256,address,uint256)"(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      recipient?: PromiseOrValue<string> | null,
      amount?: null
    ): FundsDisbursedEventFilter;
    FundsDisbursed(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      recipient?: PromiseOrValue<string> | null,
      amount?: null
    ): FundsDisbursedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "PublisherBanned(address,string)"(
      publisher?: PromiseOrValue<string> | null,
      reason?: null
    ): PublisherBannedEventFilter;
    PublisherBanned(
      publisher?: PromiseOrValue<string> | null,
      reason?: null
    ): PublisherBannedEventFilter;

    "PublisherSubscribed(address,string[],uint256)"(
      publisher?: PromiseOrValue<string> | null,
      sites?: null,
      subscriptionDate?: null
    ): PublisherSubscribedEventFilter;
    PublisherSubscribed(
      publisher?: PromiseOrValue<string> | null,
      sites?: null,
      subscriptionDate?: null
    ): PublisherSubscribedEventFilter;

    "PublisherUnbanned(address)"(
      publisher?: PromiseOrValue<string> | null
    ): PublisherUnbannedEventFilter;
    PublisherUnbanned(
      publisher?: PromiseOrValue<string> | null
    ): PublisherUnbannedEventFilter;

    "SiteAdded(address,string)"(
      publisher?: PromiseOrValue<string> | null,
      site?: null
    ): SiteAddedEventFilter;
    SiteAdded(
      publisher?: PromiseOrValue<string> | null,
      site?: null
    ): SiteAddedEventFilter;

    "SiteRemoved(address,string)"(
      publisher?: PromiseOrValue<string> | null,
      site?: null
    ): SiteRemovedEventFilter;
    SiteRemoved(
      publisher?: PromiseOrValue<string> | null,
      site?: null
    ): SiteRemovedEventFilter;

    "SupportedTokenAdded(address)"(
      token?: PromiseOrValue<string> | null
    ): SupportedTokenAddedEventFilter;
    SupportedTokenAdded(
      token?: PromiseOrValue<string> | null
    ): SupportedTokenAddedEventFilter;

    "SupportedTokenRemoved(address)"(
      token?: PromiseOrValue<string> | null
    ): SupportedTokenRemovedEventFilter;
    SupportedTokenRemoved(
      token?: PromiseOrValue<string> | null
    ): SupportedTokenRemovedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    activeCampaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addSite(
      _site: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addSupportedToken(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    banUser(
      _user: PromiseOrValue<string>,
      _reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    bannedUsers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    campaignCount(overrides?: CallOverrides): Promise<BigNumber>;

    campaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimOrderCount(overrides?: CallOverrides): Promise<BigNumber>;

    claimOrders(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collectFees(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createCampaign(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createClaimOrder(
      _campaignId: PromiseOrValue<BigNumberish>,
      _requestedAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    disburseFunds(
      _campaignId: PromiseOrValue<BigNumberish>,
      _recipient: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    editCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      _newDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    feePercent(overrides?: CallOverrides): Promise<BigNumber>;

    getActiveCampaignsCount(overrides?: CallOverrides): Promise<BigNumber>;

    getCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getClaimOrder(
      _orderId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPublisher(
      _publisher: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPublisherSites(
      _publisher: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSupportedTokens(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalProtocolFees(overrides?: CallOverrides): Promise<BigNumber>;

    isPublisher(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isUserBanned(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pauseCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    processClaimOrder(
      _orderId: PromiseOrValue<BigNumberish>,
      _approvedAmount: PromiseOrValue<BigNumberish>,
      _rejected: PromiseOrValue<boolean>,
      _reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    protocolFees(overrides?: CallOverrides): Promise<BigNumber>;

    publishers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeSite(
      _siteIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeSupportedToken(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    resumeCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFeePercent(
      _feePercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    subscribePublisher(
      _sites: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supportedTokensList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unbanUser(
      _user: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    activeCampaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addSite(
      _site: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addSupportedToken(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    banUser(
      _user: PromiseOrValue<string>,
      _reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    bannedUsers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaignCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    campaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimOrderCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claimOrders(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    collectFees(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createCampaign(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createClaimOrder(
      _campaignId: PromiseOrValue<BigNumberish>,
      _requestedAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    disburseFunds(
      _campaignId: PromiseOrValue<BigNumberish>,
      _recipient: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    editCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      _newDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    feePercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getActiveCampaignsCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getClaimOrder(
      _orderId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPublisher(
      _publisher: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPublisherSites(
      _publisher: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSupportedTokens(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalProtocolFees(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPublisher(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isUserBanned(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pauseCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    processClaimOrder(
      _orderId: PromiseOrValue<BigNumberish>,
      _approvedAmount: PromiseOrValue<BigNumberish>,
      _rejected: PromiseOrValue<boolean>,
      _reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    protocolFees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    publishers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeSite(
      _siteIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeSupportedToken(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    resumeCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFeePercent(
      _feePercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    subscribePublisher(
      _sites: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    supportedTokensList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unbanUser(
      _user: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
